### ISSUE TITLE
Request Error to the ML Engine prediction

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-api-nodejs-client#1249]
_From @thewozz on July 10, 2018 14:25_

I am trying to run send a request to ML Engine to have predictions of my model once I upload to the Cloud Storage. I am receiving this error. Any solution please .

```
****Error occurred:  { Error: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. Access to model denied.**
    at createError (/user_code/node_modules/googleapis/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/user_code/node_modules/googleapis/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/user_code/node_modules/googleapis/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: 2147483648,
     validateStatus: [Function],
     headers: ....**
```

### package.json
```js
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "dependencies": {
    "@google-cloud/storage": "^1.5.1",
    "firebase-admin": "^5.5.1",
    "firebase-functions": "^1.1.0",
    "google-auth-library": "^1.1.0",
    "googleapis": "^32.0.0",
    "image-size": "^0.6.1"
  },
  "private": true,
  "devDependencies": {
    "eslint": "^4.14.0"
  }
}

### index.js

```js
'use strict';

const functions = require('firebase-functions');
const gcs = require('@google-cloud/storage');
const admin = require('firebase-admin');
const exec = require('child_process').exec;
const path = require('path');
const fs = require('fs');
const {google} = require('googleapis');
const sizeOf = require('image-size');
const auth = require('google-auth-library');

admin.initializeApp(functions.config().firebase);
const db = admin.firestore();

function cmlePredict(b64img) {
    return new Promise((resolve, reject) => {
        google.auth.getApplicationDefault(function (err, authClient, projectId) {
            if (err) {
                reject(err);
            }
            if (authClient.createScopedRequired && authClient.createScopedRequired()) {
                authClient = authClient.createScoped([
                    'https://www.googleapis.com/auth/cloud-platform'
                ]);
            }

            var ml = google.ml({
                version: 'v1'
            });

            const params = {
                auth: authClient,
                name: 'projects/my-cloud/models/model_example',
                resource: {
                    instances: [
                    {
                        "inputs": {
                        "b64": b64img
                        }
                    }
                    ]
                }
            };

            ml.projects.predict(params, (err, result) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }
            });
        });
    });
}

function resizeImg(filepath) {
    return new Promise((resolve, reject) => {
        exec(`convert ${filepath} -resize 600x ${filepath}`, (err) => {
          if (err) {
            console.error('Failed to resize image', err);
            reject(err);
          } else {
            console.log('resized image successfully');
            resolve(filepath);
          }
        });
      });
}

exports.runPrediction = functions.storage.object().onFinalize((object) => {

    fs.rmdir('./tmp/', (err) => {
        if (err) {
            console.log('error deleting tmp/ dir');
        }
    });

    const fileBucket = object.bucket;
    const filePath = object.name;
    const fileName = path.basename(filePath);
    const bucket = gcs().bucket(fileBucket);
    const file = bucket.file(filePath);

    if (filePath.startsWith('images/')) {  
        const destination = '/tmp/' + fileName;
        console.log('got a new image', filePath);
        return file.download({
            destination: destination
        }).then(() => {
            if(sizeOf(destination).width > 600) {
                console.log('scaling image down...');
                return resizeImg(destination);
            } else {
                return destination;
            }
        }).then(() => {
            console.log('base64 encoding image...');
            let bitmap = fs.readFileSync(destination);
            return new Buffer(bitmap).toString('base64');
        }).then((b64string) => {
            console.log('sending image to CMLE...');
            return cmlePredict(b64string);
        }).then((result) => {
            let boxes = result.predictions[0].detection_boxes;
            let scores = result.predictions[0].detection_scores;

            console.log('got prediction with confidence: ',scores[0]);
        })
        .catch(err => {
            console.log('Error occurred: ',err);
        });
    } else {
        return 'not a new image';
    }
});
```

_Copied from original issue: google/google-auth-library-nodejs#418_

**Comment by victorgzv** [comment]
@JustinBeckwith  @thewozz did you guys manage to solve this issue?
 google.auth.getApplicationDefault is now deprecated. Any help is appreciated. Thanks

**Comment by JustinBeckwith** [comment]
Greetings folks!  This issue has been open for quite a while.  Since this issue was filed, support for passing scopes has been added to the GCE metadata server on GAE and GCF.  I suspect that will solve the issue :) Please do let me know if you're still running into problems!
