### ISSUE TITLE
Documentation is probably outdated -> samples not working

### ISSUE THREAD

**Issue by linuxbandit** [googleapis/google-api-nodejs-client#1346]
Hi!

On [this page](https://github.com/googleapis/google-api-nodejs-client/tree/master/samples/directory_v1), there is the README that explains how to create the service account and get the credentials in P12 format. However it seems to me that all examples use the credentials in JSON format (the example file `authData.json` that I should update, for instance, is never referenced?) 

As a result, the example for [group-insert](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/directory_v1/group-insert.js) is not working for me: I manage to be authenticated but the error message says "Not Authorized to access this resource/api". I kinda followed #148 and #160 to set myself up, though it's an old issue with a way old API. But the problem to me seems a problem on permission, and indeed at the beginning I did not set scopes to the client ID of my app, from the Admin console. Buuut now I did, and still it is not working. [This comment](https://github.com/googleapis/google-api-nodejs-client/issues/160#issuecomment-39087985) is what is unclear to me, yet it's probably not my case (I didn't try) because of the age of the issue.

I am not sure of the question so to not be stuck in an x-y problem I ask simply - how do I get up and running?

googleapis version: 33.0.0
Node version: 8.11.3 (from Docker image `node:8`)
npm version: 5.6.0 (from Docker image `node:8`)
OS: linux (`Linux 431b57b6e46c 4.15.0-1014-azure #14~16.04.1-Ubuntu SMP Thu Jun 14 15:42:55 UTC 2018 x86_64 GNU/Linux`)

Extra info: steps performed
1. Go on API console, created service account, enabled domain-wide delegation, downloaded JSON credentials
2. Go on Admin panel -> security settings, added client ID of the service account with relative scopes
3. Download sample  "group-insert", modified line 23 about the credentials to use my JSON cert, modified line 49 to use my domain, put JSON and js file into a docker container `node:8`, and run `node group-add.js`. 

Result: 
`You have been successfully authenticated:  { access_token: 'yK7vsvO.....j4sTUfsvR8Z.......e7T_BYpEvoE_w96U1P2w',
  token_type: 'Bearer',
  expiry_date: 1537377925000,
  id_token: undefined,
  refresh_token: 'jwt-placeholder' }
{ Error: Not Authorized to access this resource/api
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by linuxbandit** [comment]
Adding the extra information I noticed `id_token: undefined, refresh_token: 'jwt-placeholder'`, I am confused

Anyhow, in a similar direction: @IonicaBizau have you changed your code in any way for the newer versions of `googleapis`?

**Comment by linuxbandit** [comment]
Hi,

I made it work by referring to the previous examples of Ionica. [This line](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/directory_v1/group-insert.js#L34) should be the address of a user that the JWT is impersonating (with the right privileges).

**Comment by linuxbandit** [comment]
Thank you for the work,

out of curiosity: I notice that the user who has delegation over the domain is [still missing from this line](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/directory_v1/group-insert.js#L26), did it change and now it's not necessary anymore?

I will test it in a couple of weeks, but I hope you can reply earlier
