### ISSUE TITLE
Error upload and convert files

### ISSUE THREAD

**Issue by devneedzaio** [googleapis/google-api-nodejs-client#1378]
#### Environment details

OS: Ubuntu 18.04.1
Node.js version: 8.12.0
npm version: 6.2.0
googleapis version: 34.0.0

#### Steps to reproduce

I am trying to upload and convert files to drive from word to docs. it works with files less than 74KB,
there is the same issue with excel to sheets

```
 var fileMetadata = {
                "name": "file1",
                "mimeType": 'application/vnd.google-apps.document',
                "parents": [FolderDriveID]
            };
var media = {
        'mimeType': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        body: fs.createReadStream("file.docx")
      };
      drive.files.create({
        auth: oauth2Client,
        resource: fileMetadata,
        media: media,
        fields: 'id,webViewLink'
      }, function (err, file) {
        if (err) {
          // Handle error
          console.log(err);
          cb(err)
        } else {
          // console.log(file.data);
          cb(null, file.data)
        }
      });
```
if the file fits the size, it uploads and convert just fine but if it exceeds the size this is the error
```
Error: null
    at createError (...\node_modules\axios\lib\core\createError.js:16:15)
    at settle (...\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (...\node_modules\axios\lib\adapters\http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
when I omit the resource parameter it uploads ok but then I have to manually convert by drive UI.

**Comment by arielshad** [comment]
Same issue here
