### ISSUE TITLE
directory api's scope invokes error: not a valid audience string

### ISSUE THREAD

**Issue by mildc055ee** [googleapis/google-api-nodejs-client#1381]
I'm trying to get the groups of my domain using directory api.  I've got error such `invalid_scope https://www.googleapis.com/auth/admin.directory.group is not a valid audience string.`, But this scope has no typo (I copied and paste from [here](https://developers.google.com/admin-sdk/directory/v1/guides/authorizing) ).

my code 
```javascript
import { google } from 'googleapis'
const admin = google.admin({ version: 'directory_v1' })
const scopes = [
	'https://www.googleapis.com/auth/admin.directory.group',
	'https://www.googleapis.com/auth/admin.directory.group.readonly',
	'https://www.googleapis.com/auth/admin.directory.group.member',
	'https://www.googleapis.com/auth/admin.directory.group.member.readonly',
	'https://www.googleapis.com/auth/spreadsheet'
]

const jwtClient = new google.auth.JWT(
  null,
  '/path/to/service_account.json',
  null,
  scopes,
  'delegate@mydomain.com'
)

jwtClient.authorize()

admin.groups.list({
    auth: jwtClient,
    domain: 'mydomain.com'
}).then(res => {
    console.log( res.data.groups )
}).catch(err => {
    console.error( 'cannot get groups' )
})

```

#### Environment details

  - OS: windows10 home
  - Node.js version: 8.12.0
  - npm version: 6.4.1
  - yarn version: 1.9.4
  - babel-node version: 7.0.0
  - `googleapis` version: 34.0.0

#### Steps to reproduce

  1. write code
  2. exec `yarn babel-node google.js`
  3. got 

```
Error: invalid_scope: https://www.googleapis.com/auth/admin.directory.group is not a valid audience string. 
    at /mnt/c/mild/github/dashboard/node_modules/gtoken/src/index.ts:276:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Thanks!

**Comment by russellsean** [comment]
Your JWT client should contain the service account email and private key: 

```
const keys = require('/path/to/service_account.json');
const jwtClient = new google.auth.JWT(
  keys.client_email,
  null,
  keys.private_key,
  scopes,
  'delegate@mydomain.com'
)
```
Try this and report back!

**Comment by mildc055ee** [comment]
@russellsean I tried two codes, but I got same error..
It is confirmed that `key` has `service_account.json`'s data.
```javascript
import key from './service_account.json'

const jwtClient = new google.auth.JWT(
  key.client_email,
  null,
  key.private_key,
  scopes,
  'delegate@mydomain.com'
)
```

```javascript
import key from './service_account.json'
const jwtClient = new google.auth.JWT(
  key.client_email,
  '/path/to/service_account.json',
  key.private_key,
  scopes,
  'delegate@mydomain.com'
)
```

```console
Error: invalid_scope: https://www.googleapis.com/auth/admin.directory.group is not a valid audience string.
    at /mnt/c/mild/github/dashboard/node_modules/gtoken/src/index.ts:276:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: invalid_scope: https://www.googleapis.com/auth/admin.directory.group is not a valid audience string.
    at /mnt/c/mild/github/dashboard/node_modules/gtoken/src/index.ts:276:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by russellsean** [comment]
Try removing `https://www.googleapis.com/auth/admin.directory.group` from your scopes and only use `https://www.googleapis.com/auth/admin.directory.group.readonly`

Also make sure your service account has domain wide delgation.

**Comment by mildc055ee** [comment]
@russellsean Now it works! removing `/admin.directory.group` scope was effective.
However, when I tried the same scopes as first one, it works! That's a fathomless mystery…

Thanks for your help!!
