### ISSUE TITLE
Cannot convert null undefined or null to object

### ISSUE THREAD

**Issue by ynigoreyes** [googleapis/google-api-nodejs-client#1393]
#### Environment details

  - OS: macOS Mojave 10.14.1
  - Node.js version: 8.12
  - npm version: 6.4.1
  - `googleapis` version: 34
  - `firebase`: 5.5.4
  - `firebase-functions`: 2.0.5

#### Steps to reproduce

  1. created a firebase project and serving a function that uses googleapis
  2. const { google } = require('googleapis')
  3. firebase serve --only functions
  4. Errors out

Here is the really long error message
None of the errors seems to be called on my logic so i am really confused. I have resorted to backtracking everything in git

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/follow-redirects/node_modules/debug/src/node.js:49:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/follow-redirects/node_modules/debug/src/index.js:9:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/follow-redirects/index.js:6:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/lib/adapters/http.js:8:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getDefaultAdapter (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/lib/defaults.js:23:15)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/lib/defaults.js:29:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/lib/core/Axios.js:3:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/lib/axios.js:5:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)                                                                                                                                                                                              [46/1711]
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/axios/index.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/googleapis/node_modules/gcp-metadata/build/src/index.js:49:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/googleapis/node_modules/google-auth-library/build/src/auth/googleauth.js:29:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/googleapis/node_modules/google-auth-library/build/src/index.js:18:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/googleapis/build/src/googleapis.js:23:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/node_modules/googleapis/build/src/index.js:19:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/src/auth/config/oauth2.js:4:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/src/auth/auth.router.js:8:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/src/auth/auth.app.js:7:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/src/auth/index.js:1:76)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/miggylol/Projects/ttuacm-backend/index.js:10:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/miggylol/.nvm/versions/node/v8.12.0/lib/node_modules/firebase-tools/lib/triggerParser.js:21:11
    at Object.<anonymous> (/Users/miggylol/.nvm/versions/node/v8.12.0/lib/node_modules/firebase-tools/lib/triggerParser.js:75:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jdcookie** [comment]
Seeing the same issue, just started a new Create React App, tried node version 8.12 & 10.12, got the same error message basically.

**Comment by ynigoreyes** [comment]
The error was caused by not providing the client-secrets and whatnot in your environment variables

**Comment by JustinBeckwith** [comment]
Sounds like it's all figured out :) Please do let me know if you run into any other issues!
