### ISSUE TITLE
Cannot find module 'googleapis'

### ISSUE THREAD

**Issue by doyongid** [googleapis/google-api-nodejs-client#1723]
#### Environment details

  - OS:MacOS 10.14.5
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `googleapis` version: 40.0.0

#### Steps to reproduce

I just want to verify the receipt. I can not solve it for a few days. Searching for Google can not solve this problem. Please help me.

**1. sudo npm install googleapis**
```
+ googleapis@40.0.0
updated 1 package and audited 142 packages in 2.364s
found 0 vulnerabilities
```

**2. package.json**
```
{
  "name": "tool_seemile",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "googleapis": "^40.0.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

```
**3. index.js**
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const {google} = require("googleapis");
const publisher = google.androidpublisher('v2');
const authClient = new google.auth.JWT({
    email: '******',
    key: '******',
    scopes: ['https://www.googleapis.com/auth/androidpublisher']
});

admin.initializeApp();

exports.validatePurchases = functions.database
    .ref('/purchases/{uId}/{orderId}')
    .onCreate((event, context) => {
        const purchase = event.val();
        if (purchase.is_processed === true) {
            console.log('Purchase already processed!, exiting');
            return null;
        }
        const orderId = context.params.orderId;
        const dbRoot = event.ref.root;
        const package_name = purchase.package_name;
        const sku = purchase.sku;
        const my_token = purchase.token;

        authClient.authorize((err, result) => {
            if (err) {
                console.log(err);
            }
            publisher.purchases.products.get({
                auth: authClient,
                packageName: package_name,
                productId: sku,
                token: my_token
            }, (err, response) => {
                if (err) {
                    console.log(err);
                }
                // Result Status must be equals to 200 so that the purchase is valid
                if (response.status === 200) {
                    return event.ref.child('is_validated').set(true);
                } else {
                    return event.ref.child('is_validated').set(false);
                }
            });
        });
        return null;
    });
```
**4. firebase deploy --only functions**
```
i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (29.53 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 8 function validatePurchases(us-central1)...
⚠  functions[validatePurchases(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'googleapis'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:3:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)


Functions deploy had errors with the following functions:
	validatePurchases


To try redeploying those functions, run:
    firebase deploy --only functions:validatePurchases


To continue deploying other features (such as database), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.
```
**5. npm audit**
 ```
                      === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 141 scanned packages
```

**Comment by doyongid** [comment]
I'm sorry I was newbie. I should have tried within the "functions" folder.

**Comment by patskid315** [comment]
What do you mean tried within functions folder? I am on this issue now and can't figure it out.

**Comment by anandhrushikesh** [comment]
I think, he meant to install the dependencies inside the functions folder.

**Comment by Alex44lel** [comment]
> I think, he meant to install the dependencies inside the functions folder.

Yees, same happened to me
