### ISSUE TITLE
Can't use "~all" in analytics.management.webproperties.list(), regex error \d

### ISSUE THREAD

**Issue by pittersnider** [googleapis/google-api-nodejs-client#1839]
## Environment details

  - OS: Ubuntu 18
  - Node.js version: 10.15.1
  - npm version: 6.4.1
  - `googleapis` version: ^42.0.0

#### Steps to reproduce

```javascript
    async getWebProperties() {
        await jwt.authorize()
        return google
            .analytics({ version: 'v3', auth: this.authClient })
            .management
            .webproperties
            .list() // ({ accountId: '~all' }) also have problem!
            .then(output => output.data)
    }
```

According to Google's documentation, we should be able to use **~all** in **webproperties.list()**, and it works when testing via Google API Explorer. However, via Node.js, I have the below error:

```javascript
 { Error: Invalid value '~all'. Values must match the following regular expression: '\d+'
     at Gaxios.request (/app/node_modules/gaxios/build/src/gaxios.js:70:23)
     at process._tickCallback (internal/process/next_tick.js:68:7)
   response:
    { config:
       { url:
          'https://www.googleapis.com/analytics/v3/management/accounts/~all/webproperties/~all/entityAdWordsLinks',
         method: 'GET',
         paramsSerializer: [Function],
         headers: [Object],
         params: [Object: null prototype] {},
         validateStatus: [Function],
         retry: true,
         responseType: 'json',
         retryConfig: [Object] },
      data: { error: [Object] },
      headers:
       { 'alt-svc':
          'quic=":443"; ma=2592000; v="46,43",h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000',
         'cache-control': 'private, max-age=0',
         connection: 'close',
         'content-encoding': 'gzip',
         'content-type': 'application/json; charset=UTF-8',
         date: 'Mon, 30 Sep 2019 19:12:31 GMT',
         expires: 'Mon, 30 Sep 2019 19:12:31 GMT',
         server: 'GSE',
         'transfer-encoding': 'chunked',
         vary: 'Origin, X-Origin',
         'x-content-type-options': 'nosniff',
         'x-frame-options': 'SAMEORIGIN',
         'x-xss-protection': '1; mode=block' },
      status: 400,
      statusText: 'Bad Request' },
   config:
    { url:
       'https://www.googleapis.com/analytics/v3/management/accounts/~all/webproperties/~all/entityAdWordsLinks',
      method: 'GET',
      paramsSerializer: [Function],
      headers:
       { 'x-goog-api-client': 'gdcl/3.1.0 gl-node/10.15.1 auth/5.2.0',
         'Accept-Encoding': 'gzip',
         'User-Agent': 'google-api-nodejs-client/3.1.0 (gzip)',
         Authorization:
          'Bearer XXXXXXXXXXX',
         Accept: 'application/json' },
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      responseType: 'json',
      retryConfig:
       { currentRetryAttempt: 0,
         retry: 3,
         retryDelay: 100,
         httpMethodsToRetry: [Array],
         noResponseRetries: 2,
         statusCodesToRetry: [Array] } },
   code: 400,
   errors:
    [ { domain: 'global',
        reason: 'invalidParameter',
        message:
         'Invalid value \'~all\'. Values must match the following regular expression: \'\\d+\'',
        locationType: 'parameter',
        location: 'accountId' } ] }
```

**Comment by pittersnider** [comment]
Any update?

**Comment by bcoe** [comment]
@pittersnider with the tiny bit of digging I've done, it looks like the `\d+` requirement is being enforced on the server-side.

It might be worth also opening up an issue, using one of the methods [outlined here](https://developers.google.com/analytics/help).

**Comment by JustinBeckwith** [comment]
Greetings folks!  This looks to be a backend issue.  We try to keep issues in this repository focused on the node.js specific bits.  If you're stilling having issues, please follow up with [the product team](https://developers.google.com/analytics/help)!
