### ISSUE TITLE
Documentation required for making requests as a service account 

### ISSUE THREAD

**Issue by nexus-uw** [googleapis/google-api-nodejs-client#188]
Currently, only making requests as the authorized user is documented. I would like to be able to know how to properly make api calls as a service account (aka use jwt authorization). I am currently grasping at straws as every so often the library crashes due to some error in the jwt authorize call,
 see:

`````` crypto.js:398
  var ret = this._binding.sign(toBuf(key));  
                          ^
TypeError: Not a buffer  
    at Sign.sign (crypto.js:398:27)  
    at createRS256Signature (..../googleapis/node_modules/gapitoken/node_modules/jws/index.js:75:58)  
    at jwsRS256Sign (.../googleapis/node_modules/gapitoken/node_modules/jws/index.js:68:21)
    at Object.jwsSign [as sign] (.../googleapis/node_modules/gapitoken/node_modules/jws/index.js:32:12)
    at GAPI.getAccessToken (.../googleapis/node_modules/gapitoken/gapitoken.js:56:25)
    at GAPI.getToken (.../googleapis/node_modules/gapitoken/gapitoken.js:35:14)
    at JWT.refreshToken_ (.../googleapis/lib/auth/jwtclient.js:83:13)
    at .../googleapis/lib/auth/jwtclient.js:64:12
    at .../googleapis/node_modules/gapitoken/gapitoken.js:20:17
    at fs.js:266:14```


Thank you,
Simon
``````

**Comment by coreybutler** [comment]
I don't think this issue should be closed until there is something about this in the documentation. Had I not hunted through the closed issues, this information would have been lost to me.

**Comment by ryanseys** [comment]
@coreybutler Added a section to the README: https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens

Let me know if this suits your fancy.

**Comment by coreybutler** [comment]
@ryanseys - yup, thanks!
