### ISSUE TITLE
admin.groups.insert returning GaxiosError: Invalid Input: groupKey

### ISSUE THREAD

**Issue by atremarc** [googleapis/google-api-nodejs-client#1986]
I'm having an issue calling the method for inserting a new group where it seems like the error produced is asking for a param groupKey, though the docs say that the method should be looking for only an auth and requestBody param. Here is my code:

```js
//defining my groups object
const { google } = require('googleapis');
const groups = google.admin('directory_v1').groups;

//insert method call
await groups.insert({ auth: jwt,
      requestBody: {
        email: groupEmail,
        description: description,
        name: groupName
      }
    }, (err, res) => {
      if (err) return console.log('ERROR RETURNED BY GOOGLE DIRECTORY API: ', err);
      const result = res.data.name;
      console.log('Group created for: ', result);
    });
});
```

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the exact error you're getting?  

Side note - it looks like you're mixing async/await and callbacks.  I honestly don't know how this is working :)  You probably want something like:

```js
//defining my groups object
const { google } = require('googleapis');
const groups = google.admin('directory_v1').groups;

try {
  const res = await groups.insert({ 
    auth: jwt,
    requestBody: {
      email: groupEmail,
      description: description,
      name: groupName
    }
  });
  console.log(res.data);
} catch (e) {
  console.error(e);
}
```

**Comment by atremarc** [comment]
Okay, I dropped the callback and switched to the try/catch async/await syntax throughout just to be sure, and here's the complete error (minus some project specific data):

```
GaxiosError: Invalid Input: groupKey
    at Gaxios._request (/Users/atremarc/Documents/projects/happy_little_trees/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JWT.requestAsync (/Users/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:350:18)
    at async /Users/.../index.js:115:19 {
  response: {
    config: {
      url: 'https://www.googleapis.com/admin/directory/v1/groups',
      method: 'POST',
      paramsSerializer: [Function],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      body: '{"email":"...","description":"...","name":"..."}',
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000',
      'cache-control': 'private, max-age=0',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "frame-ancestors 'self'",
      'content-type': 'application/json; charset=UTF-8',
      date: 'Mon, 09 Mar 2020 17:36:33 GMT',
      expires: 'Mon, 09 Mar 2020 17:36:33 GMT',
      server: 'GSE',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'https://www.googleapis.com/admin/directory/v1/groups'
    }
  },
  config: {
    url: 'https://www.googleapis.com/admin/directory/v1/groups',
    method: 'POST',
    paramsSerializer: [Function],
    data: {
      email: '...',
      description: '...',
      name: '...'
    },
    headers: {
      'x-goog-api-client': 'gdcl/3.2.2 gl-node/12.13.0 auth/5.10.1',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/3.2.2 (gzip)',
      Authorization: 'Bearer ...',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    body: '{"email":"...","description":"...","name":"..."}',
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      domain: 'global',
      reason: 'invalid',
      message: 'Invalid Input: groupKey'
    }
  ]
}

```

**Comment by atremarc** [comment]
I figured out what was happening. The email address I was trying to create for the group was based on a database call to get some information about a college class (name, class#, subject, etc.), so I was building the email address out of some of that data. However, the name I was trying to use had some illegal characters in it (specifically spaces), so if would fail when trying to create the email, and produce this misleading error. Thanks for your time though!
