### ISSUE TITLE
API Generator Instructions Missing / Broken

### ISSUE THREAD

**Issue by grant** [googleapis/google-api-nodejs-client#2027]
Hi team!
I'm trying to run the API generator for a new API with a private discovery document. However, I'm running into a few issues.

- I can't find documentation on how to run the generator. I think it would be really useful to write this down somewhere in a README. I don't use this package enough to remember the commands.
- I'm not able to generate after a clone, `npm i`, and `npm run generate`. I get errors like this:
  -  client/samples/youtube/upload.js
    -  eslint errors: `23:26  error  "googleapis" is not found  node/no-missing-require`
    - `✖ 40 problems (40 errors, 0 warnings)`
    - I had to rmrf `samples/` for the module to build.
- There are weird fetch and access errors while generating APIs. Those should probably shouldn't be there.

`npm run generate` used to work.

Like `npm run generate https://slides.googleapis.com/$discovery/rest?version=v1`.

Now running the command fails:

```
(node:82838) UnhandledPromiseRejectionWarning: Error: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/rest?version=v1</code> was not found on this server.  <ins>That’s all we know.</ins>

    at Gaxios._request (/Users/timmerman/.../node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/Users/timmerman/.../node_modules/p-queue/dist/index.js:255:29)
(node:82838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> googleapis@48.0.0 postgenerate /...
> npm run fix


> googleapis@48.0.0 fix /...
> eslint --fix '**/*.js' && gts fix


Oops! Something went wrong! :(

ESLint: 6.8.0.

You are linting "**/*.js", but all of the files matching the glob pattern "**/*.js" are ignored.

If you don't want to lint these files, remove the pattern "**/*.js" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! googleapis@48.0.0 fix: `eslint --fix '**/*.js' && gts fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the googleapis@48.0.0 fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-04-10T01_39_35_319Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! googleapis@48.0.0 postgenerate: `npm run fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the googleapis@48.0.0 postgenerate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-04-10T01_39_35_362Z-debug.log
```

Am I missing something? I'm guessing it's just broken and there are no tests. Is there a guide for generating this client for APIs that don't get picked up by the discovery list?

**Comment by grant** [comment]
Hmm, so these are my steps:

```
# Generate Client
git clone https://github.com/googleapis/google-api-nodejs-client
cd google-api-nodejs-client
npm i
rm -rf samples
npm run pregenerate
npm run generate $DISCOVERY
npm run postgenerate
```

It looks like it might work (still deleting `samples/`) with a public discovery but not my discovery.

I think the tool must assume my discovery URL is in a certain format. This is mine:

```
https://SERVICE.googleapis.com/$discovery/rest?version=v1&key=MY_KEY
```

For example, `https://www.googleapis.com/discovery/v1/apis/photoslibrary/v1/rest` works, but my discovery (private API) doesn't.

The tool is probably modifying my URL/stripping my API key causing the 404.

**Comment by grant** [comment]
It look like some client might not be able to see the discovery url. Is there a way to directly provide a discovery doc json file?
