### ISSUE TITLE
 TypeError: Cannot read property 'context' of undefined at getProfile 

### ISSUE THREAD

**Issue by pavitra15** [googleapis/google-api-nodejs-client#2850]
TypeError: Cannot read property 'context' of undefined at getProfile (/workspace/node_modules/googleapis/build/src/apis/gmail/v1.js:77:31)
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at /workspace/node_modules/pify/index.js:32:6
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at new Promise (<anonymous>)
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at /workspace/node_modules/pify/index.js:6:9
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at ret (/workspace/node_modules/pify/index.js:56:76)
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at Object.exports.getEmailAddress (/workspace/lib/oauth.js:43:48)
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at /workspace/index.js:65:40
Default
2021-11-19 12:43:07.959 ISToauth2callback93yqt44os60j at processTicksAndRejections (internal/process/task_queues.js:95:5)

Any one has any idea? it was working earlier!! suddenly code is not working!!

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the code you're using to get this error?  Any steps to reproduce the problem?

**Comment by pavitra15** [comment]
refereing below code

https://github.com/GoogleCloudPlatform/cloud-functions-gmail-nodejs

**Comment by pavitra15** [comment]
So what is the alternative for this??

**Comment by mesuttalebi** [comment]
Is there any alternative to continue working...?
