### ISSUE TITLE
Cannot do auth (authclient or JWT Auth) on Node 18 - ERR_OSSL_UNSUPPORTED

### ISSUE THREAD

**Issue by Aldo111** [googleapis/google-api-nodejs-client#2965]
I have a service account that I'm trying to use, via node, to read a spreadsheet.

When I authenticate with either of the two ways (the first one is what I used as recently as late 2021).
```
const auth = new google.Auth.GoogleAuth({
  credentials: credentials, //JSON.parse(process.env.SHEET_CREDENTIALS),
  scopes: 'https://www.googleapis.com/auth/spreadsheets',
});

this.authClient = (await auth.getClient()) as google.Auth.Compute;
```
or
```
 const jwtAuth = new google.google.auth.JWT(
      credentials.client_email,
      null,
      credentials.private_key,
      ['https://www.googleapis.com/auth/spreadsheet']
  );
await jwtAuth.authorize();
```

I get the following error message when trying to read the spreadsheet with either auth initialized.
```
Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (D:\wamp64\www\azarroland-repo\admin-api\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (D:\wamp64\www\azarroland-repo\admin-api\node_modules\jws\lib\sign-stream.js:32:24)
    at GoogleToken.requestToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:225:31)
    at GoogleToken.getTokenAsyncInner (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:163:21)
    at GoogleToken.getTokenAsync (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:142:55)
    at GoogleToken.getToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:94:21)
    at JWT.refreshTokenNoCache (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\jwtclient.js:171:36)
    at JWT.refreshToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\oauth2client.js:145:25)
    at JWT.authorizeAsync (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\jwtclient.js:152:35)
```

Actually, with jwtAuth.authorize, I get the above error the moment it tries to authorize (whereas with the authClient, I get the error when it tries to execute the spreadsheet read api request)

1) Is this a client library issue or a product issue?
This is the client library for auth

2) Did someone already solve this?
I tried to search but I didn't see any similar issues yet.

3) Do you have a support contract?

#### Environment details

  - OS: Windows
  - Node.js version: 18
  - `googleapis` version: 100

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by Aldo111** [comment]
I actually get a bit more to the error if I catch/log it:

```
Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (D:\wamp64\www\azarroland-repo\admin-api\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (D:\wamp64\www\azarroland-repo\admin-api\node_modules\jws\lib\sign-stream.js:32:24)
    at GoogleToken.requestToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:225:31)      
    at GoogleToken.getTokenAsyncInner (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:163:21)
    at GoogleToken.getTokenAsync (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:142:55)     
    at GoogleToken.getToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\gtoken\build\src\index.js:94:21)
    at JWT.refreshTokenNoCache (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\jwtclient.js:171:36)
    at JWT.refreshToken (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\oauth2client.js:145:25)
    at JWT.authorizeAsync (D:\wamp64\www\azarroland-repo\admin-api\node_modules\google-auth-library\build\src\auth\jwtclient.js:152:35) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
```

  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'

**Comment by Aldo111** [comment]
Downgrading to Node 16.15 pointed out the real issue was with my "private_key". There was a point at which I encoded/decode the whole service account credentials in JSON and it looks like that added bad characters to the key contents.
