### ISSUE TITLE
Access Token not attaching to the Headers

### ISSUE THREAD

**Issue by melkorCBA** [googleapis/google-api-nodejs-client#3026]
I am implementing a flow to update a specific doc in  user's drive. I am having an issue using the acquired access token to do the operation on the server side  :
- What I am trying to do 
I have acquired the access token with relevant scopes from the Oauth2 Auth code flow using
[google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs).  This token is sent to a backed (message queue) that uses the google docs and google drive libraries to execute the operation.
- What code you've already tried

This is the drive service.

```javaScript
const { google } = require("googleapis");
const drive = google.drive({ version: "v3" });

const folder = (() => {
  const create = async ({ parentId, name }) => {
    try {
      const response = await drive.files.create({
        resource: {
          name,
          parents: [parentId],
          mimeType: "application/vnd.google-apps.folder",
        },
        fields: "id",
      });
      return response;
    } catch (err) {
      console.log('----Erorors')
      console.log(err.response.config);
      throw new Error(err);
    }
  };
  return {
    create,
  };
})();
// attaching the accses token to the headers
const setAuth = ({accessToken}) => {
  google.options({headers: {Authorization: `Bearer ${accessToken}`}})
};

module.exports = (authData) => {
  setAuth(authData);
  return {
    folder
  };
};

```

- Any error messages you're getting
```
GaxiosError: Login Required
[2022-07-15T17:07:16.388Z]     at Gaxios._request (C:\work\hobs\cv-gen\cv-gen-process\node_modules\gaxios\build\src\gaxios.js:130:23)
[2022-07-15T17:07:16.389Z]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2022-07-15T17:07:16.391Z]     at async Object.create (C:\work\hobs\cv-gen\cv-gen-process\func-cv-gen-process\lib\drive-service.js:88:24)
[2022-07-15T17:07:16.392Z]     at async module.exports (C:\work\hobs\cv-gen\cv-gen-process\func-cv-gen-process\index.js:43:26) {
```

I then Inspected the error object.
```
 code: 401,
[2022-07-15T17:07:16.532Z]   errors: [
[2022-07-15T17:07:16.533Z]     {
[2022-07-15T17:07:16.538Z]       domain: 'global',
[2022-07-15T17:07:16.539Z]       reason: 'required',
[2022-07-15T17:07:16.541Z]       message: 'Login Required',
[2022-07-15T17:07:16.544Z]       locationType: 'header',
[2022-07-15T17:07:16.546Z]       location: 'Authorization'
[2022-07-15T17:07:16.548Z]     }
[2022-07-15T17:07:16.551Z]   ]
[2022-07-15T17:07:16.553Z] }
```
This led me to believe the token is not getting attached for some reason. So I inspected and found out it was the case.
```
  },
[2022-07-15T17:07:16.587Z]   headers: {
[2022-07-15T17:07:16.588Z]     'x-goog-api-client': 'gdcl/6.0.0 gl-node/14.17.3 auth/8.1.1',
[2022-07-15T17:07:16.590Z]     'Accept-Encoding': 'gzip',
[2022-07-15T17:07:16.592Z]     'User-Agent': 'google-api-nodejs-client/6.0.0 (gzip)',
[2022-07-15T17:07:16.594Z]     'Content-Type': 'application/json',
[2022-07-15T17:07:16.598Z]     Accept: 'application/json'
[2022-07-15T17:07:16.600Z]   },
```
But when I inspected the headers in Global options it was set correctly.
```js
console.log( google._options.headers)
```
```
[2022-07-15T17:07:15.885Z] {
[2022-07-15T17:07:15.886Z]   Authorization: 'Bearer '<My Token>'
[2022-07-15T17:07:15.888Z] }
```

Hope someone can help to figure out what is the exact reasons for this.
Thank you!

**Comment by sofisl** [comment]
Hi @melkorCBA, have you made sure to request the initial access token, like so? 

```
const url = oauth2Client.generateAuthUrl({
  // 'online' (default) or 'offline' (gets refresh_token)
  access_type: 'offline',

  // If you only need one scope you can pass it as a string
  scope: scopes
});
```

We have more documentation on access tokens in the [README](https://github.com/googleapis/google-api-nodejs-client#oauth2-client), and you can also reference this [oAuth2 sample](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/oauth2.js).  Hope this helps, feel free to reopen if not.

**Comment by melkorCBA** [comment]
Hi @sofisl, Sorry for the late response. After going through the code base, I found what I was looking for.
```js
drive.files.context._options["headers"] = '<Access Token>'
```
This way I don't have to create oauth2Client again and do the work using the passed token.
