### ISSUE TITLE
Sending email: precondition check failed

### ISSUE THREAD

**Issue by arunkumar413** [googleapis/google-api-nodejs-client#3030]
Hello Team,

I'm trying to send an email using  API but getting `precondition check failed` error. Could  you please help me. 

Also is there is simpler way to specify the email body (raw) other than using the base encoding. The requirement is for sending email verification links.

```
(node:31540) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
GaxiosError: Precondition check failed.
    at Gaxios._request (/home/arun/projects/expressJsTemplate/node_modules/gaxios/build/src/gaxios.js:130:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/home/arun/projects/expressJsTemplate/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
    at async module.exports.VerifyEmail (/home/arun/projects/expressJsTemplate/controllers/authController.js:245:17) {
```

Here is the code 
```

    const auth = new google.auth.GoogleAuth({
      keyFile: '/path/to/json',
      scopes: ['https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.compose', 'https://www.googleapis.com/auth/gmail.metadata', 'https://www.googleapis.com/auth/gmail.modify'],
    });

    const authClient = await auth.getClient();
    google.options({ auth: authClient });

    const apis = google.getSupportedAPIs();
    const gmail = google.gmail('v1');

    let raw = makeBody('receiver@gmail.com', 'sender@gmail.com', 'verify your email', 'Here is your verification link');

    const res = await gmail.users.messages.send({
      auth: auth,
      userId: 'me',
      requestBody: {
        raw: raw,
      }
    })

```

```
// ################# Make body #################


function makeBody(to, from, subject, message) {
  var str = ["Content-Type: text/plain; charset=\"UTF-8\"\n",
    "MIME-Version: 1.0\n",
    "Content-Transfer-Encoding: 7bit\n",
    "to: ", to, "\n",
    "from: ", from, "\n",
    "subject: ", subject, "\n\n",
    message
  ].join('');

  var encodedMail = new Buffer(str).toString("base64").replace(/\+/g, '-').replace(/\//g, '_');
  return encodedMail;
}

```

**Comment by sofisl** [comment]
Hi @arunkumar413, I'd encourage you to take a look at this sample that seemed to work [well for me](https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/gmail/send.js). Feel free to open a bug if you notice there's something wrong!
