### ISSUE TITLE
Cannot create google calender event with attendees

### ISSUE THREAD

**Issue by mster429** [googleapis/google-api-nodejs-client#3543]
I am trying to create a google calender event from my nodejs (ts) backend using a google service account.

```
import { google } from 'googleapis';
import { GoogleAuth } from 'google-auth-library';

const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/calendar.events'],
      keyFile: './src/serviceaccount.json',
});

const calendar = google.calendar({ version: 'v3', auth: auth });
const apiResponse = await calendar.events.insert({
      calendarId: "a@gmail.com",
      sendUpdates: 'all',
      requestBody: {
        start: {
          dateTime: "2024-08-22T06:00:00Z",
          timeZone: 'Japan',
        },
        end: {
          dateTime: "2024-08-22T06:30:00Z",
          timeZone: 'Japan',
        },
        attendees: [{ email: "a@gmail.com" }, { email: "b@gmail.com" }],
        summary: 'Test Event',
        description: 'Test Event created from api',
        anyoneCanAddSelf: false,
        created: new Date().toISOString(),
        guestsCanInviteOthers: false,
        guestsCanModify: false,
        reminders: {
          useDefault: true,
        },
        visibility: 'default',
      }
    });

    console.log(apiResponse);
```

But executing this results in the following error

```
GaxiosError: Service accounts cannot invite attendees without Domain-Wide Delegation of Authority.
    at Gaxios._request (/home/mahendra/Habitto/flex-test-ts/my-app/node_modules/gaxios/build/src/gaxios.js:142:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/home/mahendra/Habitto/flex-test-ts/my-app/node_modules/google-auth-library/build/src/auth/oauth2client.js:429:18)
    at async createEvent (file:///home/mahendra/Habitto/flex-test-ts/my-app/dist/main.js:47:29)
    at async main (file:///home/mahendra/Habitto/flex-test-ts/my-app/dist/main.js:10:5) {

  error: undefined,
  status: 403,
  code: 403,
  errors: [
    {
      domain: 'calendar',
      reason: 'forbiddenForServiceAccounts',
      message: 'Service accounts cannot invite attendees without Domain-Wide Delegation of Authority.'
    }
  ],
  [Symbol(gaxios-gaxios-error)]: '6.7.1'
}
```
a@gmail.com is my own email address added to the google service account.
Both a@gmail.com and b@gmail.com are owners in the service account and the domain wide delegation is enabled with necessary calender permissions and the calenders has been shared as well. When I remove the
 `attendees: [{ email: "a@gmail.com" }, { email: "b@gmail.com" }]`
parameter from the request body it is creating the event without any issues in the a@gmail.com calender. 

Couldn't find any way to delegate the authority with nodejs the official documentation had only java and python examples

What I am doing wrong here to include attendees in the event. Any help is appreciated. Thanks in advance

**Comment by mster429** [comment]
Found the solution on this thread

https://github.com/googleapis/google-auth-library-nodejs/issues/916
